apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
  namespace: ${CLUSTER_NAME}
  labels:
    ccm: azure
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 100.96.0.0/11
    services:
      cidrBlocks:
      - 100.64.0.0/13
  controlPlaneEndpoint:
    host: 192.168.101.224
    port: 6443
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: KThreesControlPlane
    name: ${CLUSTER_NAME}-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: VSphereCluster
    name: ${CLUSTER_NAME}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: VSphereCluster
metadata:
  name: ${CLUSTER_NAME}
  namespace: ${CLUSTER_NAME}
spec:
  controlPlaneEndpoint:
    host: 192.168.101.224
    port: 6443
  server: telco-res-vcenter.telcocloud.com
  thumbprint: ""
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: KThreesControlPlane
metadata:
  name: ${CLUSTER_NAME}-control-plane
  namespace: ${CLUSTER_NAME}
spec:
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: VSphereMachineTemplate
    name: ${CLUSTER_NAME}-control-plane
  kthreesConfigSpec:
    files:
    - content: |
        apiVersion: v1
        kind: Pod
        metadata:
          creationTimestamp: null
          name: kube-vip
          namespace: kube-system
        spec:
          tolerations:
            - key: node.cloudprovider.kubernetes.io/uninitialized
              value: "true"
              effect: NoSchedule
            - key: node-role.kubernetes.io/master
              effect: NoSchedule
          containers:
          - args:
            - start
            env:
            - name: vip_arp
              value: "true"
            - name: vip_leaderelection
              value: "true"
            - name: address
              value: 192.168.101.224
            - name: vip_interface
              value: eth0
            - name: vip_leaseduration
              value: "15"
            - name: vip_renewdeadline
              value: "10"
            - name: vip_retryperiod
              value: "2"
            image: projects.registry.vmware.com/tkg/kube-vip:v0.3.3_vmware.1
            imagePullPolicy: IfNotPresent
            name: kube-vip
            resources: {}
            securityContext:
              capabilities:
                add:
                - NET_ADMIN
                - SYS_TIME
            volumeMounts:
            - mountPath: /etc/kubernetes/admin.conf
              name: kubeconfig
          hostNetwork: true
          volumes:
          - hostPath:
              path: /etc/rancher/k3s/k3s.yaml
              type: FileOrCreate
            name: kubeconfig
        status: {}
      owner: root:root
      path: /var/lib/rancher/k3s/server/manifests/kube-vip.yaml
    preK3sCommands:
    - hostname "testk3s"
    - echo "::1         ipv6-localhost ipv6-loopback" >/etc/hosts
    - echo "127.0.0.1   localhost" >>/etc/hosts
    - echo "127.0.0.1   {{ ds.meta_data.hostname }}" >>/etc/hosts
    - echo "testk3s" >/etc/hostname
    - grep -q -e 'primary-nics=eth0' /etc/vmware-tools/tools.conf || sed -i '/guestinfo/a
      primary-nics=eth0' /etc/vmware-tools/tools.conf
    - systemctl restart vmtoolsd
    - useradd -m test -p $1$xyz$4jfsyCqeX7YjcodykY1rB1 -g users
  replicas: 1
  version: v1.21.6+k3s1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: VSphereMachineTemplate
metadata:
  name: ${CLUSTER_NAME}-control-plane
  namespace: ${CLUSTER_NAME}
spec:
  template:
     spec:
      cloneMode: fullClone
      datacenter: Telco Cloud Datacenter
      datastore: vSAN-Datastore
      diskGiB: 50
      folder: Telco-K8S-Workload Cluster
      memoryMiB: 16384
      network:
        devices:
        - dhcp4: true
          networkName: /Telco Cloud Datacenter/network/K8S-MGMT-NW-101.x
      numCPUs: 8
      resourcePool: /Telco Cloud Datacenter/host/Compute Cluster/Resources/Telco-K8S-Workload
        Cluster
      server: telco-res-vcenter.telcocloud.com
      template: photon-3-kube-v1.20.5-vmware.2-tkg.1.3.1-18430851
---
